"""Add indexes, FK cascade rules, and bidirectional relationships.

Revision ID: 0043_indexes_cascades
Revises: c4e2f7a9b1d6, f4c8a2d6b9e1
Create Date: 2026-04-26 00:00:00.000000

This migration is the merge point for the two open Alembic heads
(``c4e2f7a9b1d6`` collaboration line and ``f4c8a2d6b9e1`` monitor line) and at
the same time applies a batch of schema improvements:

1. **Indexes** — adds covering / single-column indexes that the application
   already filters/sorts on:
     - ``ix_config_presets_org_default`` on (org_id, is_default)
     - ``ix_comments_user_id``, ``ix_comments_assigned_to``,
       ``ix_comments_resolved_by``
     - ``ix_attorney_feedback_analysis_id``,
       ``ix_attorney_feedback_created_at``

2. **Foreign-key cascades** — replaces FK constraints that previously had no
   ``ON DELETE`` action with explicit ``CASCADE`` (for owned children) or
   ``SET NULL`` (for audit/reference columns and ownership-style links the
   application wants to survive a user deletion):

     * ``CASCADE``: comments/pipeline_events/export_jobs/monitor_alerts/
       attorney_feedback/analysis_reviewer_decisions/analysis_review_statuses
       on ``analysis_id``; comments.parent_id; comment_assignment_events and
       comment_thread_escalations on ``comment_id`` / ``analysis_id``;
       notifications.user_id; monitor_alerts.monitor_id.
     * ``SET NULL``: analyses.initiated_by / flagged_by / batch_id;
       analyses.audit_logs ``user_id`` / ``analysis_id``;
       comments.user_id / resolved_by / assigned_to / assigned_by;
       attorney_feedback.user_id; export_jobs.user_id; monitors.user_id;
       monitors.source_analysis_id; monitor_alerts.dismissed_by;
       config_presets.created_by; api_keys.user_id;
       comment_thread_escalations.review_handoff_comment_id;
       comment_assignment_events.assigned_to / assigned_by;
       batch_analyses.user_id.

   The Postgres default constraint name pattern ``<table>_<column>_fkey`` is
   assumed (no named constraints exist in the prior migrations).

The migration is hand-written (not autogenerated) per repo policy and is
idempotent under downgrade.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0043_indexes_cascades"
down_revision: str | Sequence[str] | None = ("c4e2f7a9b1d6", "f4c8a2d6b9e1")
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# (table, fk_column, referenced_table, ondelete)  — used to rebuild FKs.
# ---------------------------------------------------------------------------

# CASCADE: child rows are tightly owned by the parent and should be deleted
# when the parent is deleted.
_FKS_CASCADE: list[tuple[str, str, str]] = [
    ("comments", "analysis_id", "analyses"),
    ("comments", "parent_id", "comments"),
    ("pipeline_events", "analysis_id", "analyses"),
    ("export_jobs", "analysis_id", "analyses"),
    ("monitor_alerts", "monitor_id", "monitors"),
    ("notifications", "user_id", "users"),
    ("attorney_feedback", "analysis_id", "analyses"),
    ("analysis_reviewer_decisions", "analysis_id", "analyses"),
    ("analysis_review_statuses", "analysis_id", "analyses"),
    ("comment_assignment_events", "comment_id", "comments"),
    ("comment_assignment_events", "analysis_id", "analyses"),
    ("comment_thread_escalations", "comment_id", "comments"),
    ("comment_thread_escalations", "analysis_id", "analyses"),
]

# SET NULL: reference columns where the row should outlive its referent.
_FKS_SET_NULL: list[tuple[str, str, str]] = [
    ("analyses", "initiated_by", "users"),
    ("analyses", "flagged_by", "users"),
    ("analyses", "batch_id", "batch_analyses"),
    ("audit_logs", "user_id", "users"),
    ("audit_logs", "analysis_id", "analyses"),
    ("comments", "user_id", "users"),
    ("comments", "resolved_by", "users"),
    ("comments", "assigned_to", "users"),
    ("comments", "assigned_by", "users"),
    ("attorney_feedback", "user_id", "users"),
    ("export_jobs", "user_id", "users"),
    ("monitors", "user_id", "users"),
    ("monitors", "source_analysis_id", "analyses"),
    ("monitor_alerts", "dismissed_by", "users"),
    ("config_presets", "created_by", "users"),
    ("api_keys", "user_id", "users"),
    ("comment_thread_escalations", "review_handoff_comment_id", "comments"),
    ("comment_assignment_events", "assigned_to", "users"),
    ("comment_assignment_events", "assigned_by", "users"),
    ("batch_analyses", "user_id", "users"),
]


def _fk_name(table: str, column: str) -> str:
    """Default Postgres FK constraint naming convention used by SQLAlchemy."""
    return f"{table}_{column}_fkey"


def _replace_fk(table: str, column: str, referent: str, ondelete: str | None) -> None:
    """Drop the existing FK on ``(table, column)`` and recreate with ``ondelete``.

    Uses ``IF EXISTS`` so the migration tolerates the (rare) case where the
    constraint name doesn't match the default convention.  Re-creation is
    unconditional; if it fails, the migration aborts and surfaces the issue.
    """
    op.drop_constraint(_fk_name(table, column), table, type_="foreignkey")
    op.create_foreign_key(
        _fk_name(table, column),
        table,
        referent,
        [column],
        ["id"],
        ondelete=ondelete,
    )


def _restore_fk(table: str, column: str, referent: str) -> None:
    """Drop the ON-DELETE FK and recreate without it (downgrade helper)."""
    op.drop_constraint(_fk_name(table, column), table, type_="foreignkey")
    op.create_foreign_key(
        _fk_name(table, column),
        table,
        referent,
        [column],
        ["id"],
    )


# ---------------------------------------------------------------------------
# Indexes
# ---------------------------------------------------------------------------

_NEW_INDEXES: list[tuple[str, str, list[str]]] = [
    ("ix_config_presets_org_default", "config_presets", ["org_id", "is_default"]),
    ("ix_comments_user_id", "comments", ["user_id"]),
    ("ix_comments_assigned_to", "comments", ["assigned_to"]),
    ("ix_comments_resolved_by", "comments", ["resolved_by"]),
    ("ix_attorney_feedback_analysis_id", "attorney_feedback", ["analysis_id"]),
    ("ix_attorney_feedback_created_at", "attorney_feedback", ["created_at"]),
]


def upgrade() -> None:
    # 1) Indexes — additive, safe to apply first.
    for name, table, cols in _NEW_INDEXES:
        op.create_index(name, table, cols)

    # 2) Replace FK constraints with cascade rules.
    for table, column, referent in _FKS_CASCADE:
        _replace_fk(table, column, referent, ondelete="CASCADE")

    for table, column, referent in _FKS_SET_NULL:
        _replace_fk(table, column, referent, ondelete="SET NULL")


def downgrade() -> None:
    # 1) Restore FK constraints to their prior (no on-delete action) form.
    #    Reverse order is not strictly required but keeps the diff readable.
    for table, column, referent in reversed(_FKS_SET_NULL):
        _restore_fk(table, column, referent)

    for table, column, referent in reversed(_FKS_CASCADE):
        _restore_fk(table, column, referent)

    # 2) Drop indexes added by upgrade().
    for name, table, _cols in reversed(_NEW_INDEXES):
        op.drop_index(name, table_name=table)
