// Praviar Page Layout
// US Letter with asymmetric margins (binding edge wider), header/footer.
//
// Usage: #import "layout.typ": apply-layout
// Call as `#show: apply-layout.with(branding: branding-dict)`

#import "colors.typ": ink, muted, border
#import "typography.typ": font-heading, font-body, size-caption

// ── Apply Layout ───────────────────────────────────────────────────────────

#let apply-layout(doc, branding: (:)) = {
  // Resolve page size from branding config
  let page-size = branding.at("page_size", default: "us-letter")

  // Header text: server-governed neutral marking or firm name
  let header-left = branding.at("header_text", default: "Praviar FTO Analysis")
  let header-right = "CONFIDENTIAL"
  let legal-marking = branding.at("legal_marking", default: "CONFIDENTIAL DRAFT")
  header-right = legal-marking

  // Footer text
  let footer-left = branding.at("footer_text", default: "CONFIDENTIAL -- Generated by Praviar")

  set page(
    paper: page-size,
    margin: (
      top: 1.0in,
      bottom: 1.0in,
      inside: 1.25in,
      outside: 1.0in,
    ),
    header: context {
      // Skip header on first page (cover page)
      if counter(page).get().first() > 1 {
        set text(font: font-heading, size: 7.5pt, fill: muted)
        grid(
          columns: (1fr, 1fr),
          align: (left, right),
          header-left,
          text(weight: "bold", fill: ink)[#header-right],
        )
        v(2pt)
        line(length: 100%, stroke: 0.4pt + border)
      }
    },
    footer: context {
      // Skip footer on first page (cover page)
      if counter(page).get().first() > 1 {
        line(length: 100%, stroke: 0.4pt + border)
        v(2pt)
        set text(font: font-body, size: 7pt, fill: muted)
        grid(
          columns: (1fr, auto),
          align: (left, right),
          footer-left,
          [Page #counter(page).display("1 of 1", both: true)],
        )
      }
    },
  )

  doc
}
