// Praviar Cover Page
// Centered layout with title, compound name, classification, optional logo/structure.

#import "../lib/colors.typ": ink, deep-teal, accent, muted, border, surface
#import "../lib/typography.typ": font-heading, font-body, font-mono
#import "../lib/utils.typ": fmt-date

#let render-cover(data, branding, assets-dir) = {
  // Suppress headers/footers on cover page (handled by page counter check in layout)
  set page(header: none, footer: none)

  let compound = data.at("compound", default: (:))
  let compound-name = compound.at("name", default: "Unknown Compound")
  let report-id = data.at("report_id", default: "N/A")
  let generated = data.at("generated_at", default: none)
  let version = data.at("praviar_pipeline_version", default: "")
  let firm-name = branding.at("firm_name", default: none)
  let fallback-display-name = if firm-name != none { firm-name } else { "Praviar" }
  let display-name = branding.at("display_name", default: fallback-display-name)
  let hide-branding = branding.at("hide_praviar_pipeline_branding", default: false)
  let suppress-praviar-branding = branding.at("suppresses_praviar_branding", default: hide-branding)
  let matter-number = branding.at("matter_number", default: none)
  let prepared-by = branding.at("prepared_by", default: none)
  let logo-path = branding.at("logo_path", default: none)

  align(center)[
    #v(0.25in)

    // Logo or firm name
    #if logo-path != none {
      image(logo-path, width: 1.35in, alt: display-name + " logo")
      v(0.16in)
    } else if not suppress-praviar-branding {
      image("../brand/praviar-mark-on-light.svg", width: 0.68in, alt: "Praviar logo")
      v(0.08in)
      text(font: font-heading, size: 16pt, fill: ink, tracking: 0em, weight: "bold")[
        #display-name
      ]
      v(0.04in)
      text(font: font-body, size: 7.5pt, fill: deep-teal, tracking: 0.16em, weight: "bold")[
        FTO ANALYSIS
      ]
      v(0.24in)
    } else if firm-name != none {
      text(font: font-heading, size: 14pt, fill: deep-teal, tracking: 0.15em, weight: "regular")[
        #upper(firm-name)
      ]
      v(0.24in)
    } else {
      text(font: font-heading, size: 12pt, fill: deep-teal, tracking: 0.15em, weight: "regular")[
        FTO ANALYSIS
      ]
      v(0.24in)
    }

    // Classification banner
    #block(
      width: 100%,
      fill: ink,
      inset: (x: 0pt, y: 8pt),
    )[
      #set text(font: font-heading, size: 9pt, fill: surface, weight: "bold", tracking: 0.2em)
      #align(center)[CONFIDENTIAL DRAFT]
    ]

    #v(0.32in)

    // Title
    #text(font: font-heading, size: 26pt, weight: "bold", fill: ink)[
      Freedom-to-Operate Analysis
    ]

    #v(0.16in)

    // Subtitle
    #text(font: font-heading, size: 14pt, fill: deep-teal)[
      Patent Screening Evidence Packet
    ]

    #v(0.28in)

    // Horizontal rule
    #line(length: 3in, stroke: 1pt + accent)

    #v(0.28in)

    // Compound name
    #text(font: font-heading, size: 18pt, weight: "bold", fill: ink)[
      #compound-name
    ]

    #v(0.28in)

    // Structure image (if available)
    #{
      let structure-path = assets-dir + "/target_structure.svg"
      // The Python renderer writes this file; if it exists Typst will render it.
      // We wrap in a block that can gracefully degrade.
      let has-structure = data.at("_has_structure_image", default: false)
      if has-structure {
        block(
          stroke: 0.5pt + border,
          radius: 4pt,
          inset: 8pt,
          fill: surface,
        )[
          #image(
            structure-path,
            width: 1.75in,
            alt: "Two-dimensional chemical structure of " + compound-name,
          )
        ]
        v(0.22in)
      }
    }

    // Metadata table
    #set text(font: font-body, size: 10pt, fill: muted)

    #grid(
      columns: (auto, auto),
      column-gutter: 1em,
      row-gutter: 0.4em,
      align: (right, left),
      [*Report ID:*], text(font: font-mono, size: 9pt)[#report-id],
      [*Generated:*], [#fmt-date(generated)],
      ..if matter-number != none {
        ([*Matter No:*], [#matter-number])
      } else { () },
      ..if prepared-by != none {
        ([*Prepared By:*], [#prepared-by])
      } else { () },
    )

    #v(1fr)

    // Footer block
    #block(width: 100%)[
      #set text(size: 8pt, fill: muted)
      #if not suppress-praviar-branding [
        Generated by Praviar v#version \
      ]
      This report is an AI-assisted screening tool and does not constitute legal advice. \
      A qualified patent attorney should review all findings before making commercial decisions.
    ]
  ]

  pagebreak()
}
