export interface PrintReportBranding {
  displayName?: string;
  footerText?: string;
  suppressPraviarBranding?: boolean;
}

export function printBrandDisplayName(branding?: PrintReportBranding): string {
  const displayName = branding?.displayName?.trim();
  if (displayName) {
    return displayName;
  }
  return branding?.suppressPraviarBranding ? "FTO Analysis" : "Praviar";
}

export function printBrandHeaderLabel(branding?: PrintReportBranding): string {
  const displayName = printBrandDisplayName(branding);
  if (/\bFTO Analysis\b/i.test(displayName)) {
    return displayName;
  }
  return `${displayName} FTO Analysis`;
}

export function printBrandFooterText(branding?: PrintReportBranding): string {
  const footerText = branding?.footerText?.trim();
  if (footerText) {
    return footerText;
  }
  if (branding?.suppressPraviarBranding) {
    return (
      "This report was generated by an AI-assisted FTO screening system for " +
      "qualified counsel review. It is informational only and does not " +
      "constitute legal advice or a formal Freedom-to-Operate opinion."
    );
  }
  return (
    "This report was generated by Praviar AI-assisted FTO screening for " +
    "qualified counsel review. It is informational only and does not " +
    "constitute legal advice or a formal Freedom-to-Operate opinion."
  );
}
