"""FTO report and feedback models — output of Step 8."""

from __future__ import annotations

from praviar_pipeline.manifest import ReportManifest
from praviar_pipeline.models.analysis import PatentAnalysis, RiskLevel
from praviar_pipeline.models.audit import PipelineAuditTrail, StepTokenUsage
from praviar_pipeline.models.compound import ResolvedCompound
from praviar_pipeline.models.critic import CriticFinding, CriticReport
from praviar_pipeline.models.drawing import DrawingStructure, PatentDrawingAnalysis
from praviar_pipeline.models.equivalents import DoEAssessment
from praviar_pipeline.models.invalidity import InvalidityAssessment
from praviar_pipeline.models.report_common import (
    REPORT_DISCLAIMER,
    ActionItem,
    ActionPriority,
    ActionType,
    AnalysisFailure,
    DataLimitation,
    RiskSummary,
    SourceHealth,
    SourceHealthEntry,
    SourceStatus,
)
from praviar_pipeline.models.report_decisioning import (
    BlockerClaimRecord,
    BlockerFamilyRecord,
    CertificationScope,
    ClaimConstructionRecord,
    ClaimProgramSummary,
    ClearanceDecision,
    ClearanceDecisionAudit,
    ClearanceOutcome,
    CohortStatus,
    CommercialExposure,
    DecisionEvidenceCategory,
    DecisionEvidenceReference,
    DecisionScope,
    EvidenceCoverageSummary,
    FutureRiskFinding,
    JurisdictionDecision,
    OpinionReadiness,
    ProsecutionAmendmentEvent,
    ProsecutionContinuityEntry,
    ProsecutionDossier,
    ProsecutionFinding,
    ProsecutionOfficeActionEvent,
)
from praviar_pipeline.models.report_document import FTOReport
from praviar_pipeline.models.report_evidence import (
    AuthorityCoverage,
    ClaimProgramDecision,
    CollectionAttempt,
    CollectionTarget,
    EvidenceAdapterKind,
    EvidenceAdapterResult,
    EvidenceArtifact,
    EvidenceArtifactType,
    EvidenceAuthorityTier,
    EvidenceCollectionDirective,
    EvidenceCollectionState,
    EvidenceCollectorDefinition,
    EvidenceCollectorRun,
    EvidenceDirectivePriority,
    FamilyEvidenceRecord,
    MatterEdge,
    MatterEdgeType,
    MatterEvidenceIndex,
    MatterGraph,
    MatterGraphSummary,
    MatterNode,
    MatterNodeType,
    MatterStore,
    MatterStoreCoverageGap,
    PatentEvidenceRecord,
    RecordCompleteness,
    RecordComponentStatus,
    RecordComponentStatusValue,
    RecordContradiction,
    RecordContradictionSeverity,
    RunObservability,
)
from praviar_pipeline.models.report_feedback import AttorneyFeedback, ClaimCorrection
from praviar_pipeline.models.report_source_spans import (
    ClaimAssertionSupport,
    ClaimSourceSpanMap,
    SourceSpanReference,
)
from praviar_pipeline.models.search_loop import CoverageGap, SearchLoopResult
from praviar_pipeline.models.verification import VerificationResult

__all__ = [
    "REPORT_DISCLAIMER",
    "ActionItem",
    "ActionPriority",
    "ActionType",
    "AnalysisFailure",
    "AttorneyFeedback",
    "AuthorityCoverage",
    "BlockerClaimRecord",
    "BlockerFamilyRecord",
    "CertificationScope",
    "ClaimAssertionSupport",
    "ClaimConstructionRecord",
    "ClaimCorrection",
    "ClaimProgramDecision",
    "ClaimProgramSummary",
    "ClaimSourceSpanMap",
    "ClearanceDecision",
    "ClearanceDecisionAudit",
    "ClearanceOutcome",
    "CohortStatus",
    "CollectionAttempt",
    "CollectionTarget",
    "CommercialExposure",
    "CoverageGap",
    "CriticFinding",
    "CriticReport",
    "DataLimitation",
    "DecisionEvidenceCategory",
    "DecisionEvidenceReference",
    "DecisionScope",
    "DoEAssessment",
    "DrawingStructure",
    "EvidenceAdapterKind",
    "EvidenceAdapterResult",
    "EvidenceArtifact",
    "EvidenceArtifactType",
    "EvidenceAuthorityTier",
    "EvidenceCollectionDirective",
    "EvidenceCollectionState",
    "EvidenceCollectorDefinition",
    "EvidenceCollectorRun",
    "EvidenceCoverageSummary",
    "EvidenceDirectivePriority",
    "FTOReport",
    "FamilyEvidenceRecord",
    "FutureRiskFinding",
    "InvalidityAssessment",
    "JurisdictionDecision",
    "MatterEdge",
    "MatterEdgeType",
    "MatterEvidenceIndex",
    "MatterGraph",
    "MatterGraphSummary",
    "MatterNode",
    "MatterNodeType",
    "MatterStore",
    "MatterStoreCoverageGap",
    "OpinionReadiness",
    "PatentAnalysis",
    "PatentDrawingAnalysis",
    "PatentEvidenceRecord",
    "PipelineAuditTrail",
    "ProsecutionAmendmentEvent",
    "ProsecutionContinuityEntry",
    "ProsecutionDossier",
    "ProsecutionFinding",
    "ProsecutionOfficeActionEvent",
    "RecordCompleteness",
    "RecordComponentStatus",
    "RecordComponentStatusValue",
    "RecordContradiction",
    "RecordContradictionSeverity",
    "ReportManifest",
    "ResolvedCompound",
    "RiskLevel",
    "RiskSummary",
    "RunObservability",
    "SearchLoopResult",
    "SourceHealth",
    "SourceHealthEntry",
    "SourceSpanReference",
    "SourceStatus",
    "StepTokenUsage",
    "VerificationResult",
]
