"""Brand-governance regressions for generated report exports."""

from __future__ import annotations

import json
import re
from pathlib import Path
from xml.etree import ElementTree as ET

import pytest

from praviar_pipeline.models.analysis import RiskLevel
from praviar_pipeline.rendering.brand_mark import (
    _load_praviar_mark_svg_paths,
    render_praviar_mark_png_stream,
)
from praviar_pipeline.rendering.branding import BrandingConfig, format_artifact_title
from praviar_pipeline.rendering.design import (
    BRAND_ACCENT,
    BRAND_BORDER,
    BRAND_CHART_MINT,
    BRAND_COPPER,
    BRAND_DEEP_TEAL,
    BRAND_INK,
    BRAND_MINT,
    BRAND_ON_INK_MUTED,
    BRAND_PAPER,
    BRAND_SECONDARY_TEXT,
    BRAND_TEAL,
    RISK_BG,
    RISK_FILL,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
RENDERING_ROOT = REPO_ROOT / "praviar_pipeline" / "src" / "praviar_pipeline" / "rendering"
TEMPLATES_ROOT = RENDERING_ROOT / "templates"
PALETTE = json.loads((REPO_ROOT / "brand" / "praviar-palette.json").read_text())

PREMIUM_HEXES = {hex_color.upper() for hex_color in PALETTE["core"].values()}
SUPPORT_HEXES = {hex_color.upper() for hex_color in PALETTE["support"].values()}

EXPORT_ALLOWED_HEXES = PREMIUM_HEXES | SUPPORT_HEXES

LEGACY_VISUAL_HEXES = {
    "#0072B2",
    "#1B2A4A",
    "#3D5A80",
    "#1F4A7A",
    "#163657",
    "#4A7BAB",
    "#6B2C8A",
    "#B08D2E",
    "#E69F00",
    "#D55E00",
    "#009E73",
    "#56B4E9",
    "1F4E79",
    "FF4444",
    "FFA500",
    "90EE90",
    "98FB98",
    "C6EFCE",
    "FFEB9C",
    "FFC7CE",
    "#D49A5A",
    "#E7F5F0",
    "#EAF3EE",
    "#CFE7DE",
    "#244349",
    "#5E7271",
    "#EEF4F2",
}


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _relative_luminance(hex_color: str) -> float:
    normalized = hex_color.removeprefix("#")
    channels = [int(normalized[index : index + 2], 16) / 255 for index in range(0, 6, 2)]
    linear = [
        channel / 12.92 if channel <= 0.03928 else ((channel + 0.055) / 1.055) ** 2.4
        for channel in channels
    ]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def _contrast_ratio(foreground: str, background: str) -> float:
    foreground_luminance = _relative_luminance(foreground)
    background_luminance = _relative_luminance(background)
    lighter = max(foreground_luminance, background_luminance)
    darker = min(foreground_luminance, background_luminance)
    return (lighter + 0.05) / (darker + 0.05)


def test_default_export_branding_uses_praviar_premium_identity() -> None:
    branding = BrandingConfig()

    assert branding.display_name == "Praviar"
    assert branding.header_text == "CONFIDENTIAL DRAFT | Praviar FTO Analysis"
    assert branding.footer_text == "CONFIDENTIAL -- Generated by Praviar"
    assert branding.primary_color == "#0B1F24"
    assert branding.accent_color == "#0E6F68"


def test_white_label_mode_still_suppresses_praviar_defaults() -> None:
    branding = BrandingConfig(hide_praviar_pipeline_branding=True)

    assert branding.display_name == "FTO Analysis"
    assert branding.header_text == "CONFIDENTIAL DRAFT | FTO Analysis"
    assert branding.footer_text == "CONFIDENTIAL"

    firm_branding = BrandingConfig(
        firm_name="Baker & McKenzie LLP",
        hide_praviar_pipeline_branding=True,
    )
    assert firm_branding.display_name == "Baker & McKenzie LLP"
    assert firm_branding.header_text == ("CONFIDENTIAL DRAFT | Baker & McKenzie LLP FTO Analysis")
    assert firm_branding.footer_text == "CONFIDENTIAL"


def test_artifact_titles_do_not_duplicate_fto_wording() -> None:
    assert format_artifact_title(BrandingConfig(), "FTO Workbook") == ("Praviar FTO Workbook")
    assert (
        format_artifact_title(
            BrandingConfig(hide_praviar_pipeline_branding=True),
            "FTO Workbook",
        )
        == "FTO Analysis Workbook"
    )
    assert (
        format_artifact_title(
            BrandingConfig(firm_name="Acme Counsel"),
            "Claim Chart Export",
        )
        == "Acme Counsel Claim Chart Export"
    )


def test_custom_logo_cannot_be_paired_with_praviar_name(tmp_path: Path) -> None:
    custom_logo = tmp_path / "custom-logo.svg"
    custom_logo.write_text("<svg />", encoding="utf-8")

    with pytest.raises(
        ValueError,
        match="logo_path requires firm_name or hide_praviar_pipeline_branding",
    ):
        BrandingConfig(logo_path=str(custom_logo))


def test_custom_logo_requires_non_praviar_identity_context(tmp_path: Path) -> None:
    custom_logo = tmp_path / "custom-logo.svg"
    custom_logo.write_text("<svg />", encoding="utf-8")

    firm_branding = BrandingConfig(
        logo_path=str(custom_logo),
        firm_name="Baker & McKenzie LLP",
    )
    white_label_branding = BrandingConfig(
        logo_path=str(custom_logo),
        hide_praviar_pipeline_branding=True,
    )

    assert firm_branding.has_logo is True
    assert firm_branding.display_name == "Baker & McKenzie LLP"
    assert firm_branding.suppresses_praviar_branding is True
    assert firm_branding.footer_text == "CONFIDENTIAL"
    assert white_label_branding.has_logo is True
    assert white_label_branding.display_name == "FTO Analysis"


def test_renderer_design_constants_match_premium_palette() -> None:
    assert PALETTE["core"]["ink"] == BRAND_INK
    assert PALETTE["core"]["forensicTeal"] == BRAND_TEAL
    assert PALETTE["core"]["clinicalMint"] == BRAND_MINT
    assert PALETTE["core"]["clinicalCopper"] == BRAND_COPPER
    assert PALETTE["core"]["paper"] == BRAND_PAPER
    assert PALETTE["core"]["softMint"] == BRAND_ON_INK_MUTED
    assert PALETTE["support"]["chartMint"] == BRAND_CHART_MINT
    assert PALETTE["support"]["deepTeal"] == BRAND_DEEP_TEAL
    assert BRAND_ACCENT == BRAND_TEAL
    assert PALETTE["support"]["borderDefault"] == BRAND_BORDER
    assert PALETTE["support"]["evidenceMuted"] == BRAND_SECONDARY_TEXT

    assert RISK_FILL[RiskLevel.HIGH] == PALETTE["support"]["clinicalRed"]
    assert RISK_FILL[RiskLevel.MEDIUM] == BRAND_COPPER
    assert RISK_FILL[RiskLevel.LOW] == BRAND_TEAL
    assert RISK_FILL[RiskLevel.CLEAR] == BRAND_MINT
    assert RISK_BG[RiskLevel.MEDIUM] == PALETTE["support"]["riskMediumWash"]
    assert RISK_BG[RiskLevel.LOW] == PALETTE["core"]["softMint"]


def test_pptx_dark_cover_metadata_has_readable_contrast() -> None:
    assert _contrast_ratio(BRAND_PAPER, BRAND_INK) >= 7
    assert _contrast_ratio(BRAND_ON_INK_MUTED, BRAND_INK) >= 4.5

    intro = _read(RENDERING_ROOT / "pptx_report_intro.py")
    closing = _read(RENDERING_ROOT / "pptx_report_closing.py")
    for source in (intro, closing):
        assert "BRAND_ON_INK_MUTED" in source


def test_pdf_typst_templates_use_praviar_mark_and_premium_palette() -> None:
    cover = _read(TEMPLATES_ROOT / "components" / "cover.typ")
    appendices = _read(TEMPLATES_ROOT / "components" / "appendices.typ")
    colors = _read(TEMPLATES_ROOT / "lib" / "colors.typ")
    layout = _read(TEMPLATES_ROOT / "lib" / "layout.typ")
    report_template = _read(TEMPLATES_ROOT / "report.typ")
    mark = _read(TEMPLATES_ROOT / "brand" / "praviar-mark.svg")
    mark_on_light = _read(TEMPLATES_ROOT / "brand" / "praviar-mark-on-light.svg")

    assert 'image("../brand/praviar-mark-on-light.svg"' in cover
    assert 'image("../brand/praviar-mark-on-light.svg", width: 0.68in' in cover
    assert 'image("../brand/praviar-mark.svg"' not in cover
    assert '"Praviar"' in cover
    assert "#display-name" in cover
    assert "#upper(display-name)" not in cover
    assert "FTO ANALYSIS" in cover
    assert "Praviar Pipeline" not in cover
    assert "Praviar FTO Analysis" in layout
    assert "CONFIDENTIAL -- Generated by Praviar" in layout
    assert "render-appendices(data, branding)" in report_template
    assert "suppress-praviar-branding" in appendices
    assert "The analysis system performs automated Freedom-to-Operate screening" in appendices
    assert 'stroke="#D7ECE5"' in mark_on_light
    assert 'stroke-width="4"' in mark_on_light

    for hex_color in PREMIUM_HEXES:
        assert hex_color in colors or hex_color in mark or hex_color in mark_on_light

    for hex_color in LEGACY_VISUAL_HEXES:
        assert hex_color not in colors
        assert hex_color not in cover
        assert hex_color not in mark
        assert hex_color not in mark_on_light


def test_pdf_typst_typography_uses_resolvable_export_fonts() -> None:
    typography = _read(TEMPLATES_ROOT / "lib" / "typography.typ")

    for unresolved_family in (
        "GT Sectra",
        "Söhne",
        "Crimson Pro",
        "IBM Plex",
        "Fira Mono",
        "Inter",
        "Newsreader",
        "JetBrains Mono",
        "Helvetica",
        "Arial",
        "Georgia",
        '"serif"',
        '"sans-serif"',
        '"monospace"',
    ):
        assert unresolved_family not in typography

    for resolved_family in (
        "New Computer Modern",
        "DejaVu Sans Mono",
        "Libertinus Serif",
    ):
        assert resolved_family in typography


def test_office_mark_helper_uses_canonical_svg_path_tuples() -> None:
    mark = _read(TEMPLATES_ROOT / "brand" / "praviar-mark.svg")
    root = ET.fromstring(mark)
    expected_paths = [
        (element.attrib["d"], element.attrib["fill"])
        for element in root.iter()
        if element.tag.endswith("path")
    ]

    assert [(path.d, path.fill) for path in _load_praviar_mark_svg_paths()] == expected_paths


def test_office_export_cover_lockups_are_assertive() -> None:
    docx_frontmatter = _read(RENDERING_ROOT / "docx_report_sections_frontmatter.py")
    pptx_intro = _read(RENDERING_ROOT / "pptx_report_intro.py")

    assert "width=Inches(1.0)" in docx_frontmatter
    assert "width=Inches(1.0)" in pptx_intro


def test_office_export_mark_helper_renders_png() -> None:
    for variant in ("on_light", "on_dark"):
        stream = render_praviar_mark_png_stream(variant=variant, size_px=128)
        assert stream.getvalue().startswith(b"\x89PNG\r\n\x1a\n")


def test_export_renderers_do_not_reintroduce_legacy_visual_palette() -> None:
    scanned_suffixes = {".py", ".typ", ".svg"}
    scanned_text = "\n".join(
        _read(path)
        for path in RENDERING_ROOT.rglob("*")
        if path.is_file() and path.suffix in scanned_suffixes
    )

    for hex_color in LEGACY_VISUAL_HEXES:
        assert hex_color not in scanned_text

    assert "Praviar Pipeline v" not in scanned_text
    assert "Generated by Praviar Pipeline" not in scanned_text
    assert "Praviar Pipeline Version:" not in scanned_text


def test_export_templates_do_not_reintroduce_legacy_palette_terms() -> None:
    scanned_text = "\n".join(
        _read(path)
        for path in TEMPLATES_ROOT.rglob("*")
        if path.is_file() and path.suffix in {".typ", ".svg"}
    )
    legacy_terms = {
        "chemistry-stain",
        "methylene",
        "eosin",
        "iodine",
        "bromocresol",
        "permanganate",
        "gold-leaf",
        "judgment-copper",
        "navy",
        "steel",
        "evidence-slate",
    }

    for term in legacy_terms:
        assert term not in scanned_text.lower()


def test_export_python_uses_palette_a_vocabulary() -> None:
    scanned_text = "\n".join(_read(path) for path in RENDERING_ROOT.rglob("*.py") if path.is_file())
    legacy_vocabulary = {
        "BRAND_NAVY",
        "BRAND_STEEL",
        "add_navy_title_bar",
        "navy title bar",
    }

    for term in legacy_vocabulary:
        assert term not in scanned_text

    assert "BRAND_DEEP_TEAL" in scanned_text
    assert "add_ink_title_bar" in scanned_text


def test_export_renderer_hexes_stay_inside_documented_palette_contract() -> None:
    scanned_suffixes = {".py", ".typ", ".svg"}
    unknown_hexes: dict[str, list[str]] = {}

    for path in RENDERING_ROOT.rglob("*"):
        if not path.is_file() or path.suffix not in scanned_suffixes:
            continue
        hexes = {hex_color.upper() for hex_color in re.findall(r"#[0-9A-Fa-f]{6}", _read(path))}
        unknown = sorted(hexes - EXPORT_ALLOWED_HEXES)
        if unknown:
            unknown_hexes[str(path.relative_to(RENDERING_ROOT))] = unknown

    assert unknown_hexes == {}


def test_typst_templates_use_surface_instead_of_plain_white_fills() -> None:
    scanned_text = "\n".join(_read(path) for path in (TEMPLATES_ROOT / "components").rglob("*.typ"))
    colors = _read(TEMPLATES_ROOT / "lib" / "colors.typ")

    assert 'rgb("#FFFFFF")' not in colors
    assert "fill: white" not in scanned_text
    assert "else { white }" not in scanned_text


def test_office_and_chart_renderers_use_brand_paper_instead_of_plain_white() -> None:
    office_renderer_files = [
        "design.py",
        "docx_report_layout.py",
        "pptx_report_intro.py",
        "pptx_report_layout.py",
        "pptx_report_closing.py",
        "pptx_report_charts.py",
        "xlsx.py",
        "charts_distribution.py",
        "charts_gauge.py",
        "charts_timeline.py",
    ]
    scanned_text = "\n".join(_read(RENDERING_ROOT / file) for file in office_renderer_files)

    assert "BRAND_PAPER" in scanned_text
    for raw_white in ['"#FFFFFF"', '"FFFFFF"', '"#ffffff"', '"white"']:
        assert raw_white not in scanned_text


def test_office_export_covers_include_praviar_mark() -> None:
    docx_frontmatter = _read(RENDERING_ROOT / "docx_report_sections_frontmatter.py")
    pptx_intro = _read(RENDERING_ROOT / "pptx_report_intro.py")

    for source in (docx_frontmatter, pptx_intro):
        assert "render_praviar_mark_png_stream" in source
        assert "suppresses_praviar_branding" in source


def test_xlsx_working_sheets_keep_branded_print_identity() -> None:
    xlsx = _read(RENDERING_ROOT / "xlsx.py")

    assert "def _apply_working_sheet_branding(" in xlsx
    assert "branding.suppresses_praviar_branding" in xlsx
    assert "CONFIDENTIAL DRAFT - counsel review required" in xlsx
    assert "AI-assisted FTO screening; not a legal opinion" in xlsx
    assert "ws.print_title_rows" in xlsx
    assert "ws.auto_filter.ref =" in xlsx
    assert "get_column_letter(ws.max_column)" in xlsx
    assert "_apply_working_sheet_branding(" in xlsx
    assert 'sheet_label="Risk Matrix"' in xlsx
    assert 'sheet_label=f"Claim Chart {ia.patent_id}"' in xlsx
    assert 'sheet_label="Prior Art References"' in xlsx


def test_api_pdf_exports_use_the_branded_pipeline_renderer() -> None:
    worker = _read(REPO_ROOT / "api" / "src" / "api" / "workers" / "task_exports.py")

    assert "from praviar_pipeline.rendering.pdf import render_pdf" in worker
    assert "render_pdf(" in worker
