"""Rate limiting configuration using slowapi + Redis."""

from __future__ import annotations

import hashlib
import ipaddress
import uuid

from fastapi import Request
from slowapi import Limiter

from api.client_ip import get_client_ip
from api.config import get_settings

# Cloudflare and Cloud Armor egress CIDR ranges that are permitted to set
# X-Forwarded-For.  Requests arriving from outside these CIDRs are treated as
# direct connections; their self-reported X-Forwarded-For is ignored to prevent
# client IP spoofing.
#
# Cloudflare IPv4/IPv6 ranges: https://www.cloudflare.com/ips/
# Cloud Armor does not add additional egress IPs beyond the GFE range, which
# routes via the same Cloudflare front-layer in this deployment topology.
#
# This tuple is also imported by api.audit so both modules share a single
# authoritative allowlist.
TRUSTED_PROXY_CIDRS: tuple[ipaddress.IPv4Network | ipaddress.IPv6Network, ...] = tuple(
    ipaddress.ip_network(cidr)
    for cidr in (
        # Cloudflare IPv4
        "103.21.244.0/22",
        "103.22.200.0/22",
        "103.31.4.0/22",
        "104.16.0.0/13",
        "104.24.0.0/14",
        "108.162.192.0/18",
        "131.0.72.0/22",
        "141.101.64.0/18",
        "162.158.0.0/15",
        "172.64.0.0/13",
        "173.245.48.0/20",
        "188.114.96.0/20",
        "190.93.240.0/20",
        "197.234.240.0/22",
        "198.41.128.0/17",
        # Cloudflare IPv6
        "2400:cb00::/32",
        "2606:4700::/32",
        "2803:f800::/32",
        "2405:b500::/32",
        "2405:8100::/32",
        "2a06:98c0::/29",
        "2c0f:f248::/32",
        # RFC 1918 / loopback — allow local proxies in dev/test
        "10.0.0.0/8",
        "172.16.0.0/12",
        "192.168.0.0/16",
        "127.0.0.0/8",
        "::1/128",
    )
)


def _is_trusted_proxy(host: str) -> bool:
    """Return True if the connecting host is a trusted reverse-proxy."""
    try:
        addr = ipaddress.ip_address(host)
        return any(addr in net for net in TRUSTED_PROXY_CIDRS)
    except ValueError:
        return False


def _key_func(request: Request) -> str:
    """Rate-limit key — first layer (anonymous abuse cap).

    Praviar has a two-layer rate-limit model:
      1. This IP-based key (applied via `@limiter.limit("60/minute")` on
         public/unauthenticated routes) prevents unauthenticated abuse before
         JWT decode runs.
      2. The plan-based per-org limiter (`rate_limit_analysis` in
         `api/src/api/middleware/rate_limit.py`) applies after auth and
         enforces tenant-specific quotas tied to subscription tier.

    Both layers compose: a request must pass IP rate-limit first, then the
    per-org plan limiter once authenticated. This avoids the latency of JWT
    decode on every request while still giving per-tenant fairness.

    X-Forwarded-For is only trusted when the direct connecting address belongs
    to a configured trusted proxy CIDR. Otherwise the direct socket address is
    used. This prevents clients from forging their IP to evade rate limiting.
    """
    return get_client_ip(request)


def _public_grant_locator(request: Request) -> str:
    return str(getattr(request, "path_params", {}).get("token", "") or "")


def _public_grant_locator_digest(request: Request) -> str:
    return hashlib.sha256(_public_grant_locator(request).encode("utf-8")).hexdigest()[:24]


def public_share_rate_limit_key(request: Request) -> str:
    """Scope public-share throttling to a token digest and trusted client IP."""
    token_digest = _public_grant_locator_digest(request)
    trusted_client = get_client_ip(request)
    client_digest = hashlib.sha256(trusted_client.encode("utf-8")).hexdigest()[:24]
    return f"public-share-grant:{token_digest}:client:{client_digest}"


def public_share_challenge_rate_limit_key(request: Request) -> str:
    """Enforce one challenge budget per grant across all source addresses."""
    return f"public-share-challenge:{_public_grant_locator_digest(request)}"


def digest_unsubscribe_rate_limit_key(request: Request) -> str:
    """Enforce one abuse budget per opaque unsubscribe capability.

    The route contains only a SHA-256 locator generated by the web proxy, never
    the raw capability. Malformed locators are hashed once more so even caller-
    supplied path material cannot enter rate-limit storage or diagnostics.
    """
    raw_locator = str(getattr(request, "path_params", {}).get("token_locator", "") or "")
    normalized = raw_locator.casefold()
    if len(normalized) == 64 and all(character in "0123456789abcdef" for character in normalized):
        safe_locator = normalized
    else:
        safe_locator = hashlib.sha256(raw_locator.encode("utf-8")).hexdigest()
    return f"weekly-digest-unsubscribe:{safe_locator}"


def authenticated_org_user_rate_limit_key(request: Request) -> str:
    """Return a stable tenant-and-user key populated by an auth dependency.

    Authenticated mutation routes must not use the default IP bucket because
    corporate users commonly share one outbound NAT address. Missing or invalid
    identity state fails closed instead of silently falling back to that shared
    bucket.
    """
    state = getattr(request, "state", None)
    org_id = getattr(state, "rate_limit_org_id", None)
    user_id = getattr(state, "rate_limit_user_id", None)
    try:
        normalized_org_id = uuid.UUID(str(org_id))
        normalized_user_id = uuid.UUID(str(user_id))
    except (TypeError, ValueError) as exc:
        raise RuntimeError("authenticated rate-limit identity is unavailable") from exc
    return f"org-user:{normalized_org_id}:{normalized_user_id}"


limiter = Limiter(
    key_func=_key_func,
    storage_uri=get_settings().redis_url,
    strategy="moving-window",
)
