import { afterEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, within } from "@testing-library/react";
import "@testing-library/jest-dom";
import {
  PrintAvoidBreak,
  PrintPageBreak,
  PrintReport,
} from "@/components/report/print-report";
import { PRINT_STYLES } from "@/components/report/print-report-styles";
import { buildClaimedUseReceiptLedger } from "../fixtures/claimed-use-receipts";

afterEach(() => {
  vi.restoreAllMocks();
});

describe("PrintReport", () => {
  it("includes attributable claimed-use history in the governed print packet", () => {
    render(
      <PrintReport
        claimedUseReceiptState={{
          data: buildClaimedUseReceiptLedger(),
          isError: false,
          isLoading: false,
        }}
      >
        <div>Report body</div>
      </PrintReport>,
    );

    const ledger = screen.getByTestId("claimed-use-receipt-ledger-print");
    expect(ledger).toHaveTextContent("Claimed-use receipt history");
    expect(ledger).toHaveTextContent("US12345678A1:grant-claims");
    expect(ledger).toHaveTextContent(
      "They do not rewrite or recertify the pipeline result",
    );
    expect(PRINT_STYLES).toContain(".print-claimed-use-receipts");
  });

  it("renders the print controls, custom header content, and triggers window.print", () => {
    const printSpy = vi
      .spyOn(window, "print")
      .mockImplementation(() => undefined);

    render(
      <PrintReport
        title="Custom report"
        compoundName="Aspirin"
        date="2026-04-13"
        provenanceItems={[
          {
            label: "Report record",
            value: "PRV-2026-0142",
            detail: "Pipeline 0.9.4",
          },
          {
            label: "AI model record",
            value: "4 model roles recorded",
            detail:
              "AI-assisted decision support; counsel judgment remains separate",
          },
        ]}
      >
        <div>Report body</div>
      </PrintReport>,
    );

    expect(
      screen.getByRole("button", { name: "Print Report" }),
    ).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Print Report" })).toHaveClass(
      "min-h-11",
    );
    const preview = screen.getByRole("region", {
      name: "Print packet preview",
    });
    expect(
      within(preview).getByText("Included in print packet"),
    ).toBeInTheDocument();
    expect(
      within(preview).getByText(
        "Review reliance and provenance before printing",
      ),
    ).toBeInTheDocument();
    expect(
      within(preview).getByText("Print packet governance"),
    ).toBeInTheDocument();
    expect(
      within(preview).getByText(
        "Reliance boundary and AI provenance are inserted before report content.",
      ),
    ).toBeInTheDocument();
    expect(
      document.querySelector("[aria-label='Print packet readiness summary']"),
    ).toHaveTextContent("Print packet governance");
    expect(
      within(preview).getAllByText("Reliance boundary").length,
    ).toBeGreaterThanOrEqual(2);
    expect(
      within(preview).getByText("AI provenance and evidence scope"),
    ).toBeInTheDocument();
    expect(within(preview).getByText(/PRV-2026-0142/)).toBeInTheDocument();
    expect(
      within(preview).getByText(/4 model roles recorded/),
    ).toBeInTheDocument();
    expect(screen.getByText("Custom report")).toBeInTheDocument();
    expect(
      document.querySelector("[aria-label='Praviar FTO Analysis']"),
    ).toHaveTextContent("Praviar");
    expect(
      document.querySelector("[aria-label='Praviar FTO Analysis']"),
    ).toHaveTextContent("FTO Analysis");
    expect(
      screen.getByText("Human-review screening draft"),
    ).toBeInTheDocument();
    expect(
      screen.getByText(
        "AI-assisted screening - not legal advice or a formal Freedom-to-Operate opinion",
      ),
    ).toBeInTheDocument();
    expect(screen.getByText("Compound: Aspirin")).toBeInTheDocument();
    expect(screen.getByText("Generated: 2026-04-13")).toBeInTheDocument();
    expect(
      screen.getByText(
        "This report was generated by Praviar AI-assisted FTO screening for qualified counsel review. It is informational only and does not constitute legal advice or a formal Freedom-to-Operate opinion.",
      ),
    ).toBeInTheDocument();
    expect(
      document.querySelector(
        "[aria-label='Print report AI provenance and evidence scope']",
      ),
    ).toHaveTextContent("AI provenance and evidence scope");
    const relianceBoundary = document.querySelector(
      "[aria-label='Print report reliance boundary']",
    );
    expect(relianceBoundary).toHaveTextContent("Decision support only");
    expect(relianceBoundary).toHaveTextContent("not a legal opinion");
    expect(relianceBoundary).toHaveTextContent("AI-assisted synthesis");
    expect(relianceBoundary).toHaveTextContent("Qualified counsel sign-off");
    expect(screen.getByText("PRV-2026-0142")).toBeInTheDocument();
    expect(screen.getByText("4 model roles recorded")).toBeInTheDocument();
    expect(screen.getByText("Report body")).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Print Report" }));

    expect(printSpy).toHaveBeenCalledTimes(1);
  });

  it("can render a trusted white-label print packet without visible Praviar text", () => {
    render(
      <PrintReport
        title="White-label report"
        branding={{
          displayName: "Acme Counsel",
          suppressPraviarBranding: true,
        }}
      >
        <div>Report body</div>
      </PrintReport>,
    );

    expect(screen.getByText("Acme Counsel FTO Analysis")).toBeInTheDocument();
    expect(
      document.querySelector("[aria-label='Print report reliance boundary']"),
    ).toHaveTextContent("not a legal opinion");
    expect(
      screen.getByText(
        "This report was generated by an AI-assisted FTO screening system for qualified counsel review. It is informational only and does not constitute legal advice or a formal Freedom-to-Operate opinion.",
      ),
    ).toBeInTheDocument();
    expect(screen.queryByText(/Praviar/)).not.toBeInTheDocument();
  });

  it("uses the default title when no title prop is provided", () => {
    render(
      <PrintReport>
        <div>Report body</div>
      </PrintReport>,
    );

    expect(screen.getByText("FTO Analysis Report")).toBeInTheDocument();
    expect(
      screen.getAllByText("Print packet governance").length,
    ).toBeGreaterThanOrEqual(1);
    expect(
      document.querySelector("[aria-label='Print report reliance boundary']"),
    ).toHaveTextContent("Reliance boundary");
    expect(
      screen.getByText("Model and source metadata were not included."),
    ).toBeInTheDocument();
  });

  it("can hide the visible print trigger when a page already provides one", () => {
    render(
      <PrintReport showButton={false}>
        <div>Report body</div>
      </PrintReport>,
    );

    expect(
      screen.queryByRole("button", { name: "Print Report" }),
    ).not.toBeInTheDocument();
    expect(
      screen.queryByRole("region", { name: "Print packet preview" }),
    ).not.toBeInTheDocument();
    expect(screen.getByText("Report body")).toBeInTheDocument();
  });

  it("can show the print packet preview when the page owns the print trigger", () => {
    render(
      <PrintReport showButton={false} showPacketPreview>
        <div>Report body</div>
      </PrintReport>,
    );

    expect(
      screen.queryByRole("button", { name: "Print Report" }),
    ).not.toBeInTheDocument();
    expect(
      screen.getByRole("region", { name: "Print packet preview" }),
    ).toHaveTextContent("Model and source metadata were not included.");
  });

  it("keeps long print titles, compound names, and provenance values wrappable", () => {
    const longTitle =
      "Freedom-to-operate reliance packet for a very long therapeutic candidate name with jurisdictional appendix references";
    const longCompound =
      "N-(4-((7-methoxyquinazolin-4-yl)oxy)-3-chlorophenyl)-6-acrylamidohexanamide-extended-salt-form";

    render(
      <PrintReport
        title={longTitle}
        compoundName={longCompound}
        provenanceItems={[
          {
            label: "Model and retrieval ledger",
            value:
              "model-role-primary-report-synthesis-with-very-long-run-id-PRV-2026-0142-alpha-beta-gamma",
            detail:
              "Includes source ledger, model role manifest, citation map, reviewer checkpoint, and jurisdiction caveat reconciliation.",
          },
        ]}
      >
        <div>Report body</div>
      </PrintReport>,
    );

    expect(screen.getByText(longTitle)).toHaveStyle("overflow-wrap: anywhere");
    expect(screen.getByText(`Compound: ${longCompound}`)).toHaveStyle(
      "overflow-wrap: anywhere",
    );
    expect(
      screen.getByRole("region", { name: "Print packet preview" }),
    ).toHaveTextContent("model-role-primary-report-synthesis");
  });

  it("renders the page break utility components with the expected classes", () => {
    render(
      <>
        <PrintPageBreak />
        <PrintAvoidBreak>
          <span>Keep together</span>
        </PrintAvoidBreak>
      </>,
    );

    expect(document.querySelector(".print-page-break")).toBeInTheDocument();
    expect(document.querySelector(".print-avoid-break")).toHaveTextContent(
      "Keep together",
    );
  });

  it("does not hide semantic report headers and footers in print", () => {
    expect(PRINT_STYLES).not.toMatch(/\n\s*header,\n/u);
    expect(PRINT_STYLES).not.toMatch(/\n\s*footer,\n/u);
    expect(PRINT_STYLES).not.toMatch(/\n\s*aside,\n/u);
    expect(PRINT_STYLES).toContain(".praviar-sidebar-field");
    expect(PRINT_STYLES).toContain(".print-reliance-banner");
    expect(PRINT_STYLES).toContain(".print-provenance-strip");
    expect(PRINT_STYLES).toContain(".print-packet-summary");
    expect(PRINT_STYLES).toContain("print-color-adjust: exact");
    expect(PRINT_STYLES).toContain(
      "grid-template-columns: repeat(2, minmax(0, 1fr))",
    );
    expect(PRINT_STYLES).not.toContain(
      "grid-template-columns: repeat(4, minmax(0, 1fr))",
    );
  });

  it("preserves evidence-bearing buttons in printed packets", () => {
    expect(PRINT_STYLES).toContain(
      "button:not([data-print-trigger]):not([data-print-content])",
    );
    expect(PRINT_STYLES).toContain("button[data-print-content]");
    expect(PRINT_STYLES).toContain("display: flex !important");
  });

  it("uses paged-media grids and atomic records for decision-grade PDFs", () => {
    expect(PRINT_STYLES).toContain(
      '[data-testid="counsel-next-actions"] > ul > li',
    );
    expect(PRINT_STYLES).toContain("minmax(7.5rem, 0.72fr)");
    expect(PRINT_STYLES).toContain(
      "[data-claim-coordinate] > details > [data-print-claim-layers]",
    );
    expect(PRINT_STYLES).toContain("grid-template-columns: minmax(0, 1fr)");
    expect(PRINT_STYLES).toContain("[data-print-citation-verifier-grid]");
    expect(PRINT_STYLES).toContain("[data-print-verification-checks-grid]");
    expect(PRINT_STYLES).toContain("break-inside: avoid-page !important");
    expect(PRINT_STYLES).toContain(
      ".print-report-wrapper .recharts-responsive-container",
    );
    expect(PRINT_STYLES).toContain("max-height: 175px !important");
    expect(PRINT_STYLES).toContain('input[aria-label="Evidence search query"]');
    expect(PRINT_STYLES).toContain("#tabpanel-meta .space-y-6 > * + *");
    expect(PRINT_STYLES).toContain("[data-print-keep-together]");
    expect(PRINT_STYLES).toContain("[data-print-claim-coordinate-header]");
    expect(PRINT_STYLES).toContain("margin: 0 0 7px !important");
    expect(PRINT_STYLES).toContain("[data-print-redundant-disclaimer]");
    expect(PRINT_STYLES).toContain(
      'dl[aria-label="Claim review queue summary"]',
    );
    expect(PRINT_STYLES).toContain(".print-footer");
    expect(PRINT_STYLES).toContain("position: static !important");
    expect(PRINT_STYLES).toContain(".print-footer p");
    expect(PRINT_STYLES).toContain("margin: 0 !important");
    expect(PRINT_STYLES).not.toContain(
      ".print-report-wrapper:has(#tabpanel-claims) > .print-footer",
    );
    expect(PRINT_STYLES).toContain(
      '[aria-label="Evidence workbench findings table"] table',
    );
    expect(PRINT_STYLES).toContain("table-layout: fixed !important");
    expect(PRINT_STYLES).toContain("td:last-child");
  });
});
